# Generated by Django 4.2.8 on 2024-04-11 09:17

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_oath', models.BooleanField(default=False)),
                ('booth_name', models.CharField(default=None, max_length=15, null=True)),
                ('bank_name', models.CharField(default=None, max_length=30, null=True)),
                ('banker_name', models.CharField(default=None, max_length=5, null=True)),
                ('account_number', models.CharField(default=None, max_length=30, null=True)),
                ('booth_image_url', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BoothMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=10, null=True)),
                ('menu_name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('menu_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booth_menu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booth_menu',
            },
            managers=[
                ('objects', accounts.models.BoothMenuManager()),
            ],
        ),
    ]
