# Generated by Django 4.2.8 on 2024-04-07 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothMenu',
            fields=[
                ('menu_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('menu_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('menu_image_url', models.URLField()),
                ('booth_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
